export { default as Login } from './Login'
export { default as Applications } from './Applications'
export { default as Navbar } from './Navbar'
export { default as Settings } from './Settings'
export { default as Devices } from './Devices'
export { default as Landing } from './Landing'
